development:
  clients:
    default:
      database: dozentron_result_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: dozentron_result_development
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: dozentron_result_production
      hosts:
        - localhost:27017